/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppCursosRouteImport } from './routes/app.cursos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminComentariosRouteImport } from './routes/admin.comentarios'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AppBlogIndexRouteImport } from './routes/app.blog.index'
import { Route as AdminCursosIndexRouteImport } from './routes/admin.cursos.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AppPlayerLessonIdRouteImport } from './routes/app.player.$lessonId'
import { Route as AppCursoSlugRouteImport } from './routes/app.curso.$slug'
import { Route as AppBlogSlugRouteImport } from './routes/app.blog.$slug'
import { Route as ApiWebhooksPaysuiteRouteImport } from './routes/api.webhooks.paysuite'
import { Route as AdminCursosIdRouteImport } from './routes/admin.cursos.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRoute,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPlayerLessonIdRoute = AppPlayerLessonIdRouteImport.update({
  id: '/player/$lessonId',
  path: '/player/$lessonId',
  getParentRoute: () => AppRoute,
} as any)
const AppCursoSlugRoute = AppCursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksPaysuiteRoute = ApiWebhooksPaysuiteRouteImport.update({
  id: '/api/webhooks/paysuite',
  path: '/api/webhooks/paysuite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdRoute = AdminCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/api/webhooks/paysuite': typeof ApiWebhooksPaysuiteRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/curso/$slug': typeof AppCursoSlugRoute
  '/app/player/$lessonId': typeof AppPlayerLessonIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/app/blog/': typeof AppBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/api/webhooks/paysuite': typeof ApiWebhooksPaysuiteRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/curso/$slug': typeof AppCursoSlugRoute
  '/app/player/$lessonId': typeof AppPlayerLessonIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/cursos': typeof AdminCursosIndexRoute
  '/app/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/api/webhooks/paysuite': typeof ApiWebhooksPaysuiteRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/curso/$slug': typeof AppCursoSlugRoute
  '/app/player/$lessonId': typeof AppPlayerLessonIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/app/blog/': typeof AppBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/como-funciona'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/registo'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termos-de-uso'
    | '/admin/alunos'
    | '/admin/comentarios'
    | '/admin/configuracoes'
    | '/admin/pagamentos'
    | '/api/upload'
    | '/app/catalogo'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/perfil'
    | '/blog/$slug'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/cursos/$id'
    | '/api/webhooks/paysuite'
    | '/app/blog/$slug'
    | '/app/curso/$slug'
    | '/app/player/$lessonId'
    | '/admin/blog/'
    | '/admin/cursos/'
    | '/app/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/registo'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termos-de-uso'
    | '/admin/alunos'
    | '/admin/comentarios'
    | '/admin/configuracoes'
    | '/admin/pagamentos'
    | '/api/upload'
    | '/app/catalogo'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/perfil'
    | '/blog/$slug'
    | '/admin'
    | '/app'
    | '/blog'
    | '/admin/blog/$id'
    | '/admin/cursos/$id'
    | '/api/webhooks/paysuite'
    | '/app/blog/$slug'
    | '/app/curso/$slug'
    | '/app/player/$lessonId'
    | '/admin/blog'
    | '/admin/cursos'
    | '/app/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/como-funciona'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/registo'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termos-de-uso'
    | '/admin/alunos'
    | '/admin/comentarios'
    | '/admin/configuracoes'
    | '/admin/pagamentos'
    | '/api/upload'
    | '/app/catalogo'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/perfil'
    | '/blog/$slug'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/cursos/$id'
    | '/api/webhooks/paysuite'
    | '/app/blog/$slug'
    | '/app/curso/$slug'
    | '/app/player/$lessonId'
    | '/admin/blog/'
    | '/admin/cursos/'
    | '/app/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  CursosRoute: typeof CursosRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RegistoRoute: typeof RegistoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosRoute: typeof SobreNosRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiWebhooksPaysuiteRoute: typeof ApiWebhooksPaysuiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/blog/': {
      id: '/app/blog/'
      path: '/blog'
      fullPath: '/app/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/cursos/': {
      id: '/admin/cursos/'
      path: '/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/player/$lessonId': {
      id: '/app/player/$lessonId'
      path: '/player/$lessonId'
      fullPath: '/app/player/$lessonId'
      preLoaderRoute: typeof AppPlayerLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/curso/$slug': {
      id: '/app/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/app/curso/$slug'
      preLoaderRoute: typeof AppCursoSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/$slug': {
      id: '/app/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/app/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/paysuite': {
      id: '/api/webhooks/paysuite'
      path: '/api/webhooks/paysuite'
      fullPath: '/api/webhooks/paysuite'
      preLoaderRoute: typeof ApiWebhooksPaysuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id': {
      id: '/admin/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AdminCursosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminCursosIdRoute: typeof AdminCursosIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminComentariosRoute: AdminComentariosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminCursosIdRoute: AdminCursosIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCursosRoute: typeof AppCursosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppCursoSlugRoute: typeof AppCursoSlugRoute
  AppPlayerLessonIdRoute: typeof AppPlayerLessonIdRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogoRoute: AppCatalogoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCursosRoute: AppCursosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppCursoSlugRoute: AppCursoSlugRoute,
  AppPlayerLessonIdRoute: AppPlayerLessonIdRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  CursosRoute: CursosRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RegistoRoute: RegistoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosRoute: SobreNosRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiUploadRoute: ApiUploadRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiWebhooksPaysuiteRoute: ApiWebhooksPaysuiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
