/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorPanelRouteImport } from './routes/tutor-panel'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorPanelIndexRouteImport } from './routes/tutor-panel.index'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TutorRegistroRouteImport } from './routes/tutor.registro'
import { Route as TutorPagamentoRouteImport } from './routes/tutor.pagamento'
import { Route as TutorPanelFinanceiroRouteImport } from './routes/tutor-panel.financeiro'
import { Route as TutorPanelAlunosRouteImport } from './routes/tutor-panel.alunos'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppCursosRouteImport } from './routes/app.cursos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppComunidadeRouteImport } from './routes/app.comunidade'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AdminTutoresRouteImport } from './routes/admin.tutores'
import { Route as AdminSaquesRouteImport } from './routes/admin.saques'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminEbooksRouteImport } from './routes/admin.ebooks'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminComunidadeRouteImport } from './routes/admin.comunidade'
import { Route as AdminComentariosRouteImport } from './routes/admin.comentarios'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as TutorPanelCursosIndexRouteImport } from './routes/tutor-panel.cursos.index'
import { Route as AppBlogIndexRouteImport } from './routes/app.blog.index'
import { Route as AdminMapasMentaisIndexRouteImport } from './routes/admin.mapas-mentais.index'
import { Route as AdminCursosIndexRouteImport } from './routes/admin.cursos.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as TutorPanelCursosIdRouteImport } from './routes/tutor-panel.cursos.$id'
import { Route as AppPlayerLessonIdRouteImport } from './routes/app.player.$lessonId'
import { Route as AppCursoSlugRouteImport } from './routes/app.curso.$slug'
import { Route as AppBlogSlugRouteImport } from './routes/app.blog.$slug'
import { Route as AdminMapasMentaisIdRouteImport } from './routes/admin.mapas-mentais.$id'
import { Route as AdminCursosIdRouteImport } from './routes/admin.cursos.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const TutorPanelRoute = TutorPanelRouteImport.update({
  id: '/tutor-panel',
  path: '/tutor-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorPanelIndexRoute = TutorPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorPanelRoute,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/ebooks/',
  path: '/ebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TutorRegistroRoute = TutorRegistroRouteImport.update({
  id: '/tutor/registro',
  path: '/tutor/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorPagamentoRoute = TutorPagamentoRouteImport.update({
  id: '/tutor/pagamento',
  path: '/tutor/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorPanelFinanceiroRoute = TutorPanelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => TutorPanelRoute,
} as any)
const TutorPanelAlunosRoute = TutorPanelAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => TutorPanelRoute,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/ebooks/$slug',
  path: '/ebooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComunidadeRoute = AppComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutoresRoute = AdminTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaquesRoute = AdminSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEbooksRoute = AdminEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComunidadeRoute = AdminComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const TutorPanelCursosIndexRoute = TutorPanelCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => TutorPanelRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRoute,
} as any)
const AdminMapasMentaisIndexRoute = AdminMapasMentaisIndexRouteImport.update({
  id: '/mapas-mentais/',
  path: '/mapas-mentais/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const TutorPanelCursosIdRoute = TutorPanelCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => TutorPanelRoute,
} as any)
const AppPlayerLessonIdRoute = AppPlayerLessonIdRouteImport.update({
  id: '/player/$lessonId',
  path: '/player/$lessonId',
  getParentRoute: () => AppRoute,
} as any)
const AppCursoSlugRoute = AppCursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AdminMapasMentaisIdRoute = AdminMapasMentaisIdRouteImport.update({
  id: '/mapas-mentais/$id',
  path: '/mapas-mentais/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosIdRoute = AdminCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/tutor-panel': typeof TutorPanelRouteWithChildren
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/comunidade': typeof AdminComunidadeRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/admin/tutores': typeof AdminTutoresRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/tutor-panel/alunos': typeof TutorPanelAlunosRoute
  '/tutor-panel/financeiro': typeof TutorPanelFinanceiroRoute
  '/tutor/pagamento': typeof TutorPagamentoRoute
  '/tutor/registro': typeof TutorRegistroRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/tutor-panel/': typeof TutorPanelIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/admin/mapas-mentais/$id': typeof AdminMapasMentaisIdRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/curso/$slug': typeof AppCursoSlugRoute
  '/app/player/$lessonId': typeof AppPlayerLessonIdRoute
  '/tutor-panel/cursos/$id': typeof TutorPanelCursosIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/mapas-mentais/': typeof AdminMapasMentaisIndexRoute
  '/app/blog/': typeof AppBlogIndexRoute
  '/tutor-panel/cursos/': typeof TutorPanelCursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/comunidade': typeof AdminComunidadeRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/admin/tutores': typeof AdminTutoresRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/tutor-panel/alunos': typeof TutorPanelAlunosRoute
  '/tutor-panel/financeiro': typeof TutorPanelFinanceiroRoute
  '/tutor/pagamento': typeof TutorPagamentoRoute
  '/tutor/registro': typeof TutorRegistroRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/ebooks': typeof EbooksIndexRoute
  '/tutor-panel': typeof TutorPanelIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/admin/mapas-mentais/$id': typeof AdminMapasMentaisIdRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/curso/$slug': typeof AppCursoSlugRoute
  '/app/player/$lessonId': typeof AppPlayerLessonIdRoute
  '/tutor-panel/cursos/$id': typeof TutorPanelCursosIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/cursos': typeof AdminCursosIndexRoute
  '/admin/mapas-mentais': typeof AdminMapasMentaisIndexRoute
  '/app/blog': typeof AppBlogIndexRoute
  '/tutor-panel/cursos': typeof TutorPanelCursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/tutor-panel': typeof TutorPanelRouteWithChildren
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/comunidade': typeof AdminComunidadeRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/admin/tutores': typeof AdminTutoresRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/tutor-panel/alunos': typeof TutorPanelAlunosRoute
  '/tutor-panel/financeiro': typeof TutorPanelFinanceiroRoute
  '/tutor/pagamento': typeof TutorPagamentoRoute
  '/tutor/registro': typeof TutorRegistroRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/tutor-panel/': typeof TutorPanelIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cursos/$id': typeof AdminCursosIdRoute
  '/admin/mapas-mentais/$id': typeof AdminMapasMentaisIdRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/curso/$slug': typeof AppCursoSlugRoute
  '/app/player/$lessonId': typeof AppPlayerLessonIdRoute
  '/tutor-panel/cursos/$id': typeof TutorPanelCursosIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/mapas-mentais/': typeof AdminMapasMentaisIndexRoute
  '/app/blog/': typeof AppBlogIndexRoute
  '/tutor-panel/cursos/': typeof TutorPanelCursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/como-funciona'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/registo'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termos-de-uso'
    | '/tutor-panel'
    | '/admin/alunos'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/comentarios'
    | '/admin/comunidade'
    | '/admin/configuracoes'
    | '/admin/ebooks'
    | '/admin/pagamentos'
    | '/admin/saques'
    | '/admin/tutores'
    | '/api/upload'
    | '/app/biblioteca'
    | '/app/catalogo'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/perfil'
    | '/blog/$slug'
    | '/ebooks/$slug'
    | '/tutor-panel/alunos'
    | '/tutor-panel/financeiro'
    | '/tutor/pagamento'
    | '/tutor/registro'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/ebooks/'
    | '/tutor-panel/'
    | '/admin/blog/$id'
    | '/admin/cursos/$id'
    | '/admin/mapas-mentais/$id'
    | '/app/blog/$slug'
    | '/app/curso/$slug'
    | '/app/player/$lessonId'
    | '/tutor-panel/cursos/$id'
    | '/admin/blog/'
    | '/admin/cursos/'
    | '/admin/mapas-mentais/'
    | '/app/blog/'
    | '/tutor-panel/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/registo'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termos-de-uso'
    | '/admin/alunos'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/comentarios'
    | '/admin/comunidade'
    | '/admin/configuracoes'
    | '/admin/ebooks'
    | '/admin/pagamentos'
    | '/admin/saques'
    | '/admin/tutores'
    | '/api/upload'
    | '/app/biblioteca'
    | '/app/catalogo'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/perfil'
    | '/blog/$slug'
    | '/ebooks/$slug'
    | '/tutor-panel/alunos'
    | '/tutor-panel/financeiro'
    | '/tutor/pagamento'
    | '/tutor/registro'
    | '/admin'
    | '/app'
    | '/blog'
    | '/ebooks'
    | '/tutor-panel'
    | '/admin/blog/$id'
    | '/admin/cursos/$id'
    | '/admin/mapas-mentais/$id'
    | '/app/blog/$slug'
    | '/app/curso/$slug'
    | '/app/player/$lessonId'
    | '/tutor-panel/cursos/$id'
    | '/admin/blog'
    | '/admin/cursos'
    | '/admin/mapas-mentais'
    | '/app/blog'
    | '/tutor-panel/cursos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/como-funciona'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/registo'
    | '/reset-password'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre-nos'
    | '/termos-de-uso'
    | '/tutor-panel'
    | '/admin/alunos'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/comentarios'
    | '/admin/comunidade'
    | '/admin/configuracoes'
    | '/admin/ebooks'
    | '/admin/pagamentos'
    | '/admin/saques'
    | '/admin/tutores'
    | '/api/upload'
    | '/app/biblioteca'
    | '/app/catalogo'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/perfil'
    | '/blog/$slug'
    | '/ebooks/$slug'
    | '/tutor-panel/alunos'
    | '/tutor-panel/financeiro'
    | '/tutor/pagamento'
    | '/tutor/registro'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/ebooks/'
    | '/tutor-panel/'
    | '/admin/blog/$id'
    | '/admin/cursos/$id'
    | '/admin/mapas-mentais/$id'
    | '/app/blog/$slug'
    | '/app/curso/$slug'
    | '/app/player/$lessonId'
    | '/tutor-panel/cursos/$id'
    | '/admin/blog/'
    | '/admin/cursos/'
    | '/admin/mapas-mentais/'
    | '/app/blog/'
    | '/tutor-panel/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  CursosRoute: typeof CursosRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RegistoRoute: typeof RegistoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosRoute: typeof SobreNosRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TutorPanelRoute: typeof TutorPanelRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EbooksSlugRoute: typeof EbooksSlugRoute
  TutorPagamentoRoute: typeof TutorPagamentoRoute
  TutorRegistroRoute: typeof TutorRegistroRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor-panel': {
      id: '/tutor-panel'
      path: '/tutor-panel'
      fullPath: '/tutor-panel'
      preLoaderRoute: typeof TutorPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor-panel/': {
      id: '/tutor-panel/'
      path: '/'
      fullPath: '/tutor-panel/'
      preLoaderRoute: typeof TutorPanelIndexRouteImport
      parentRoute: typeof TutorPanelRoute
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tutor/registro': {
      id: '/tutor/registro'
      path: '/tutor/registro'
      fullPath: '/tutor/registro'
      preLoaderRoute: typeof TutorRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/pagamento': {
      id: '/tutor/pagamento'
      path: '/tutor/pagamento'
      fullPath: '/tutor/pagamento'
      preLoaderRoute: typeof TutorPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor-panel/financeiro': {
      id: '/tutor-panel/financeiro'
      path: '/financeiro'
      fullPath: '/tutor-panel/financeiro'
      preLoaderRoute: typeof TutorPanelFinanceiroRouteImport
      parentRoute: typeof TutorPanelRoute
    }
    '/tutor-panel/alunos': {
      id: '/tutor-panel/alunos'
      path: '/alunos'
      fullPath: '/tutor-panel/alunos'
      preLoaderRoute: typeof TutorPanelAlunosRouteImport
      parentRoute: typeof TutorPanelRoute
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/ebooks/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comunidade': {
      id: '/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AppComunidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutores': {
      id: '/admin/tutores'
      path: '/tutores'
      fullPath: '/admin/tutores'
      preLoaderRoute: typeof AdminTutoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/saques': {
      id: '/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AdminSaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ebooks': {
      id: '/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AdminEbooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comunidade': {
      id: '/admin/comunidade'
      path: '/comunidade'
      fullPath: '/admin/comunidade'
      preLoaderRoute: typeof AdminComunidadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tutor-panel/cursos/': {
      id: '/tutor-panel/cursos/'
      path: '/cursos'
      fullPath: '/tutor-panel/cursos/'
      preLoaderRoute: typeof TutorPanelCursosIndexRouteImport
      parentRoute: typeof TutorPanelRoute
    }
    '/app/blog/': {
      id: '/app/blog/'
      path: '/blog'
      fullPath: '/app/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/mapas-mentais/': {
      id: '/admin/mapas-mentais/'
      path: '/mapas-mentais'
      fullPath: '/admin/mapas-mentais/'
      preLoaderRoute: typeof AdminMapasMentaisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos/': {
      id: '/admin/cursos/'
      path: '/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tutor-panel/cursos/$id': {
      id: '/tutor-panel/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/tutor-panel/cursos/$id'
      preLoaderRoute: typeof TutorPanelCursosIdRouteImport
      parentRoute: typeof TutorPanelRoute
    }
    '/app/player/$lessonId': {
      id: '/app/player/$lessonId'
      path: '/player/$lessonId'
      fullPath: '/app/player/$lessonId'
      preLoaderRoute: typeof AppPlayerLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/curso/$slug': {
      id: '/app/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/app/curso/$slug'
      preLoaderRoute: typeof AppCursoSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/$slug': {
      id: '/app/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/app/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/mapas-mentais/$id': {
      id: '/admin/mapas-mentais/$id'
      path: '/mapas-mentais/$id'
      fullPath: '/admin/mapas-mentais/$id'
      preLoaderRoute: typeof AdminMapasMentaisIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos/$id': {
      id: '/admin/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AdminCursosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminComunidadeRoute: typeof AdminComunidadeRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEbooksRoute: typeof AdminEbooksRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminSaquesRoute: typeof AdminSaquesRoute
  AdminTutoresRoute: typeof AdminTutoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminCursosIdRoute: typeof AdminCursosIdRoute
  AdminMapasMentaisIdRoute: typeof AdminMapasMentaisIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
  AdminMapasMentaisIndexRoute: typeof AdminMapasMentaisIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminComentariosRoute: AdminComentariosRoute,
  AdminComunidadeRoute: AdminComunidadeRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEbooksRoute: AdminEbooksRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminSaquesRoute: AdminSaquesRoute,
  AdminTutoresRoute: AdminTutoresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminCursosIdRoute: AdminCursosIdRoute,
  AdminMapasMentaisIdRoute: AdminMapasMentaisIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
  AdminMapasMentaisIndexRoute: AdminMapasMentaisIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppComunidadeRoute: typeof AppComunidadeRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCursosRoute: typeof AppCursosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppCursoSlugRoute: typeof AppCursoSlugRoute
  AppPlayerLessonIdRoute: typeof AppPlayerLessonIdRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCatalogoRoute: AppCatalogoRoute,
  AppComunidadeRoute: AppComunidadeRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCursosRoute: AppCursosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppCursoSlugRoute: AppCursoSlugRoute,
  AppPlayerLessonIdRoute: AppPlayerLessonIdRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TutorPanelRouteChildren {
  TutorPanelAlunosRoute: typeof TutorPanelAlunosRoute
  TutorPanelFinanceiroRoute: typeof TutorPanelFinanceiroRoute
  TutorPanelIndexRoute: typeof TutorPanelIndexRoute
  TutorPanelCursosIdRoute: typeof TutorPanelCursosIdRoute
  TutorPanelCursosIndexRoute: typeof TutorPanelCursosIndexRoute
}

const TutorPanelRouteChildren: TutorPanelRouteChildren = {
  TutorPanelAlunosRoute: TutorPanelAlunosRoute,
  TutorPanelFinanceiroRoute: TutorPanelFinanceiroRoute,
  TutorPanelIndexRoute: TutorPanelIndexRoute,
  TutorPanelCursosIdRoute: TutorPanelCursosIdRoute,
  TutorPanelCursosIndexRoute: TutorPanelCursosIndexRoute,
}

const TutorPanelRouteWithChildren = TutorPanelRoute._addFileChildren(
  TutorPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  CursosRoute: CursosRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RegistoRoute: RegistoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosRoute: SobreNosRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TutorPanelRoute: TutorPanelRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  BlogSlugRoute: BlogSlugRoute,
  EbooksSlugRoute: EbooksSlugRoute,
  TutorPagamentoRoute: TutorPagamentoRoute,
  TutorRegistroRoute: TutorRegistroRoute,
  BlogIndexRoute: BlogIndexRoute,
  EbooksIndexRoute: EbooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
